openapi: "3.0.0"

info:
  title: "Inventory"
  description: "This is the API specification of Inventory"
  version: "1.0.0"
  contact:
    name: "Juan David González Mosquera"
    email: "juan_d.gonzalez_m@uao.edu.co"

paths:
  /returning/create:
    post:
      tags:
        - "returning"
      summary: "Create returning"
      description: "We can create returning with this service"
      operationId: "Create"
      requestBody:
        description: "returning information"
        required: true
        content: 
          application/json: 
            schema: 
              type: object
              properties: 
                state:
                  type: "string"
                  example: "funcional"
                obs:
                  type: "string"
                  example: 'Objetos devueltos en buen estado'
                borrowing_fk: 
                  type: "integer"
                  example: 4
                auth_user_fk: 
                  type: "integer"
                  example: 1
      responses:
        200:
          description: "successful operation"
          content:
            application/json:
              schema:
                type: "object"
                properties: 
                  message: 
                    type: "string"
                    example: "La solicitud de devolución se ha creado con éxito."
        409:
          description: "bad request"
          content:
            application/json:
              schema:
                type: "object"
                properties: 
                  message: 
                    type: "string"
                    example: "No es posible realizar una solicitud de devolución a un préstamo que no ha sido Aprobado."
        500: 
          description: "bad request"
          content:
            application/json:
              schema:
                type: "object"
                properties: 
                  message: 
                    type: "string"
                    example: "¡Error en el servidor!."



 
        
  

  
    
   
        
       
 
